### ISSUE TITLE
Compatibility with Character Class?

### ISSUE THREAD

**Issue by Louspirit** [NonStaticGH/CPathHostProject#4]
Hello,

I am trying to use your system to make an AI walk on the ground, walls, and ceiling (spider-like).
You are using a Float Pawn Movement to move the pawn in your examples, and they follow the path gracefully.

In actual games, we use more _Character_ than _Pawn_. It includes network replication, for example. _Character_ comes with _Character Movemen_t included. I used _Fly Movement Mode_ but it has some inertia that makes a worse path following the floating pawns. 

Do you have advices on how to use your plugin with characters?

Thanks

**Comment by NonStaticGH** [comment]
Hello, my plugin only finds a path from point A to point B, the flying pawn
I made is just for demonstration purposes. You need to implement your own
path following method. I'm sorry, I can't be of much help right now.

**Comment by Louspirit** [comment]
I removed the air control on character movement (Flying mode) and it seems to do the trick.
